# Generated by Django 2.2.5 on 2020-01-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='blog_pics')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('on_offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='blog_pics')),
                ('date', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('site', models.CharField(max_length=100)),
            ],
        ),
    ]
